FROM node:18.20.8-alpine AS build

WORKDIR /bushing_register/frontend/

RUN pwd

COPY frontend/package.json frontend/package-lock.json* /bushing_register/frontend/

RUN npm ci --silent


CMD ["npm", "run", "dev", "--", "--host", "--port", "5173"]