services:
  br_backend:
    container_name: br_backend
    restart: unless-stopped
    image: ghcr.io/zawiszowski/bushing_register-br_backend:latest
    build: 
        context: backend
        dockerfile: ./Dockerfile.prod
    platform: linux/arm64
    env_file:
      - .env
    volumes:
      - br_media:/bushing_register/backend/media
    depends_on:
      - br_database_psql

  br_frontend: 
    container_name: br_frontend
    restart: unless-stopped
    image: ghcr.io/zawiszowski/bushing_register-br_frontend:latest
    build: 
        context: ./
        dockerfile: ./frontend/Dockerfile.prod
    platform: linux/arm64
    ports:
        - 80:80
    volumes:
        - ./nginx/production:/etc/nginx/conf.d
        - br_media:/bushing_register/media
    depends_on: 
        - br_backend
  
  br_database_psql:
    image: postgres:16.2-alpine
    restart: unless-stopped
    container_name: br_database_psql
    volumes:
      - br_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.psql


volumes:
  br_media:
  br_postgres_data: