# Generated by Django 5.2.2 on 2025-06-26 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MountingComponentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bushingregister',
            name='axle',
            field=models.CharField(choices=[('Rear', 'Rear'), ('Front', 'Front')], default='Front', max_length=5),
        ),
        migrations.AlterField(
            model_name='bushingregister',
            name='mounting_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mounting_component', to='register.mountingcomponentmodel'),
        ),
        migrations.DeleteModel(
            name='MountingComponent',
        ),
    ]
